### ISSUE TITLE
no function in adminer 4.5.0

### ISSUE THREAD

**Issue by gitFrank** [jnvsor/adminer-table-header-scroll#1]
Hi, in adminer 4.3.1 this plugin works like it should.
In adminer 4.5.0 nothing happens.
Seems Content Security Policy is the reason.
"Source: function tableHeaderPositionUpdate(){ ...."

**Comment by jnvsor** [comment]
Looks like a CSP nonce was added in 4.4

Try the new master, does that work?

**Comment by jnvsor** [comment]
Fixed in 1.1

**Comment by gitFrank** [comment]
Works *thumb up*
And thank you for this very helpful plugin.

Cheers
Frank

**Comment by jnvsor** [comment]
You're welcome :)
